In [1]:
import numpy as np

In [2]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [6]:
# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [9]:
print(apartment)

# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

apartment = np.delete(apartment, [0, 1])

apartment = np.append(apartment, share_living_space)

print(apartment)

[5.950e+01 3.140e+01 1.900e+01 2.200e+01 6.055e+04 2.000e+00]
[1.90000000e+01 2.20000000e+01 6.05500000e+04 2.00000000e+00
 5.27731092e-01]


In [11]:
len(apartment)

5

In [12]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [18]:
t[6]

31

In [19]:
x = np.array([120, 150, 90])
y = np.array([130, 130, 130])
z = np.array([2, 3, 2.5])

In [21]:
z = 72 * z

In [22]:
z

array([144., 216., 180.])

In [23]:
x + y + z

array([394., 496., 400.])

In [24]:
x = np.array([4, 5])
y = np.array([2, 1])
z = np.array([1, 0])

In [25]:
2*x - 3*y + 5*z

array([7, 7])

In [28]:
x = np.array([3, 4, 5, 9])
y = np.array([1, 5, 3, 6])

In [29]:
-200*x + 400*y

array([-200, 1200,  200,  600])

## Практика. Векторы

In [1]:
import numpy as np
import pandas as pd

In [2]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [4]:
display(Hut_Paradise_DF)

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [5]:
rows = Hut_Paradise_DF.values

In [6]:
rows

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]])

In [7]:
rows[2, 3]

10

Вычислите вектор нежилой площади:

In [8]:
rows[:, 1] - rows[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

In [9]:
0.4 * rows[:, 0]

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [10]:
demo_time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [12]:
demo_two_week = rows[:, 4]

In [13]:
np.dot(demo_two_week, demo_time) 

1348

In [16]:
demo_two_week@demo_time

1348

Даны три вектора:

In [17]:
u = np.array([3, 0, 1, 1, 1])
v = np.array([0, 1, 0, 2, -2])
w = np.array([1, -4, -1, 0, -2])

Проверьте, являются ли векторы попарно ортогональными.

In [18]:
display(u@v)
display(u@w)
display(v@w)

0

0

0

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3

In [19]:
2*v - 3*w

array([-3, 14,  3,  4,  2])

In [23]:
u_norm = u/np.linalg.norm(u)
display(u_norm[2])

v_norm = v/np.linalg.norm(v)
display(v_norm[3])

w_norm = w/np.linalg.norm(w)
display(w_norm[0])

0.2886751345948129

0.6666666666666666

0.21320071635561041

## Практика. Базовые действия над матрицами

In [1]:
import numpy as np

Husband_Income = np.array([100, 220, 140])
Wife_Income = np.array([150, 200, 130])
Mother_In_Law_Income = np.array([90, 80, 100])

Husband_Сonsumption = np.array([50, 50, 60])
Wife_Сonsumption = np.array([100, 80, 140])
Mother_In_Law_Сonsumption = np.array([100, 20, 140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы

In [2]:
Inc = np.array([Husband_Income,
                Wife_Income,
                Mother_In_Law_Income]).T

In [3]:
Inc.diagonal()

array([100, 200, 100])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [4]:
Cons = np.array([Husband_Сonsumption,
                 Wife_Сonsumption,
                 Mother_In_Law_Сonsumption]).T

In [5]:
Cons.diagonal()

array([ 50,  80, 140])

In [6]:
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [7]:
0.87*Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

In [8]:
P = 0.87*Inc - Cons

In [9]:
P[2, :]

array([ 61.8, -26.9, -53. ])

### Практика. Умножение матриц

In [34]:
import numpy as np
import pandas as pd

Даны матрица A и вектор x.

In [11]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить

In [15]:
A@x

array([26, 30])

In [16]:
np.dot(A, x)

array([26, 30])

Даны две матрицы:

In [17]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [20]:
A.shape

(5, 4)

In [21]:
B.shape

(2, 5)

Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

In [23]:
np.dot(B, A)[0, 3]

14

Дана система векторов:

In [24]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [26]:
X = np.array([x, y, z]).T

In [31]:
G = X.T@X

In [32]:
np.reshape(G, (1, 9))

array([[22,  3,  0,  3,  7,  0,  0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [35]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                         'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                         'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                         'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                         'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                        }, 
                        index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра'])

Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                         'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                         'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                         'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                         'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                        }, 
                        index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя', 'Юра'])

In [36]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [37]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

Найдите вектор выручки Бориса.

In [43]:
count_boris = Count_DF.loc['Борис'].values
price_boris = Price_DF.loc['Борис'].values

In [45]:
display(count_boris)
display(price_boris)
display(count_boris * price_boris)

array([ 2, 21,  3, 25,  6])

array([1.8, 2.5, 1. , 1. , 1. ])

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [46]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [52]:
# Таблица прибыли по всем стилистам по всем услагам 
Val = Count_DF.values * Price_DF.values
display(Val)

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [55]:
# вектор прибыли салона
firm_comm = Val@com
display(firm_comm)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [58]:
# вектор коэффициентов расчета прибыли посли списания комиссии
part_com = np.array([1]*5) - com

# вектор прибыли стилистов
participants_comm = Val@part_com
display(participants_comm)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [57]:
part_com = np.array([1]*5) - com
part_com

array([0.8, 0.8, 0.7, 0.9, 0.9])

## Практика. Обратная матрица, ранг, определитель

In [1]:
import numpy as np
import pandas as pd

Дана матрица А

In [60]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите обратную матрицу к матрице А.

In [63]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [61]:
np.linalg.matrix_rank(A)

3

In [64]:
np.linalg.det(A)

32.0

Дана система векторов:

In [66]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов v1, v2, v3, v4.

In [67]:
X = np.array([v1, v2, v3, v4]).T

In [69]:
np.linalg.matrix_rank(X)

4

In [71]:
# Матрица Грамма системы векторов
G = X.T@X
display(G)

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [72]:
np.linalg.det(G)

3716647.9999999995

In [73]:
np.linalg.inv(G)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

## Решение СЛАУ

In [8]:
import numpy as np

1

In [3]:
A = np.array([[4, 7],[5, 10]])
b = np.array([20, 30])

In [4]:
A_inv = np.linalg.inv(A)

In [6]:
A_inv@b

array([-2.,  4.])

2

In [12]:
A = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])
b = np.array([1, 4, 5, 0])
display(A)
display(b)

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

array([1, 4, 5, 0])

In [13]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

In [15]:
w = A.T@b
w

array([-6, 16])